function data = clean_up_data(profiling_script_filename)

    run( profiling_script_filename )
  
    total_time = stepper;
        
    solver_time                 = zeros( size(total_time) );
    solver_invoked   = contacts > 0;
    solver_time( solver_invoked == 1 ) = solver;
        
    collision_detection_time = collision_detection;
    preprocessing_time       = collision_detection_preprocessing;
    narrow_time              = narrow_phase;
    broad_time               = broad_phase;
    contact_reduction_time   = contact_reduction;

%     kdop_work_pool_time            = collision_detection_creating_kdop_work_pool;        
%     kdop_traversal_time            = tandem_traversal;
%     kdop_traversal_launches        = tandem_traversal_invocations;
%     kdop_traversal_gpu_setup_time  = tandem_traversal_opencl_prepare_input;
%     kdop_traversal_gpu_read_time   = tandem_traversal_opencl_read_time;
%     kdop_traversal_gpu_write_time  = tandem_traversal_opencl_write_time;
%     
%     kdop_updating_time             = collision_detection_updating_kdop;
% 
%     kdop_refit_time                = refit_tree;
%     kdop_refit_launches            = refit_tree_invocations;
%     kdop_refit_gpu_setup_time      = refit_tree_opencl_prepare_input;
%     kdop_refit_gpu_cleanup_time    = refit_tree_opencl_prepare_output;
%     kdop_refit_gpu_read_time       = refit_tree_opencl_read_time;
%     kdop_refit_gpu_write_time      = refit_tree_opencl_write_time;
%     
%     transform_time                 = transform_vertices;
%     transform_launches             = transform_vertices_invocations;
%     transform_gpu_read_time        = transform_vertices_opencl_read_time;
%     transform_gpu_write_time       = transform_vertices_opencl_write_time;
%     
%     contact_launches               = exact_test_invocations;
%     contact_time                   = exact_test;
%     contact_gpu_read_time          = exact_test_opencl_read_time;
%     contact_gpu_write_time         = exact_test_opencl_write_time;
%     
%     contact_gpu_postprocess        = sort_and_report_contact_points;
    
    data = struct(...        
        'total_time', total_time,...
        'solver_time', solver_time,...         
        'collision_detection_time', collision_detection_time,...
        'preprocessing_time',preprocessing_time,...
        'narrow_time',narrow_time,...
        'broad_time',broad_time,...
        'contact_reduction_time',contact_reduction_time,...
        'contacts', contacts,...
        'minimum_penetration', minimum_penetration,...
        'maximum_penetration', maximum_penetration,...
        'average_penetration', average_penetration,...
        'rfactors', {rfactor},...
        'convergence', {convergence},...
        'divergence', div_count,...
        'rel_conv', rel_conv,...
        'abs_conv', abs_conv,...        
        'Ekin', Ekin,...        
        'Epot', Epot...
        );
%         'kdop_work_pool_time',kdop_work_pool_time,...
%         'kdop_traversal_time',kdop_traversal_time,...
%         'kdop_traversal_launches',kdop_traversal_launches,...
%         'kdop_traversal_gpu_setup_time',kdop_traversal_gpu_setup_time,...
%         'kdop_traversal_gpu_read_time',kdop_traversal_gpu_read_time,...
%         'kdop_traversal_gpu_write_time',kdop_traversal_gpu_write_time,...
%         'kdop_updating_time',kdop_updating_time,...
%         'kdop_refit_time',kdop_refit_time,...
%         'kdop_refit_launches',kdop_refit_launches,...
%         'kdop_refit_gpu_setup_time',kdop_refit_gpu_setup_time,...
%         'kdop_refit_gpu_cleanup_time',kdop_refit_gpu_cleanup_time,...
%         'kdop_refit_gpu_read_time',kdop_refit_gpu_read_time,...
%         'kdop_refit_gpu_write_time',kdop_refit_gpu_write_time,...
%         'transform_time',transform_time,...
%         'transform_launches',transform_launches,...
%         'transform_gpu_read_time',transform_gpu_read_time,...
%         'transform_gpu_write_time', transform_gpu_write_time,...
%         'contact_launches', contact_launches,...
%         'contact_time', contact_time,...
%         'contact_gpu_read_time', contact_gpu_read_time,...
%         'contact_gpu_write_time', contact_gpu_write_time,...
%         'contact_gpu_postprocess', contact_gpu_postprocess,...
end
