function make_time_slice_tabel( scenes, results, caption )

S = length(scenes);

time_data = cell(S,1);
procentage_data = cell(S,1);
mixed_data = cell(S,1);
k = 1;
for scene=1:S,
        
        measurements = results{scene};

        total_time = sum(measurements.total_time);
        solver_time = sum(measurements.solver_time);
        cd_time = sum(measurements.collision_detection_time);
        init_time = sum(measurements.preprocessing_time);
        broad_time = sum(measurements.broad_time);
        narrow_time = sum(measurements.narrow_time);
        reduction_time = sum(measurements.contact_reduction_time);
        other_time = total_time - solver_time - init_time - broad_time - narrow_time - reduction_time;
        
        timings = [
            total_time, solver_time, cd_time, init_time, broad_time, narrow_time, reduction_time, other_time
            ];
         
        % We convert time to units of minutes
        time_data{k} = round( timings /60000, 2);
        procentage_data{k} = round(100*timings ./ total_time, 2);
        
        mixed_data{k} = [ time_data{k}(1), procentage_data{k}(2:end) ];
        
        k = k + 1;
end

time_labels = {...
    'Total ($10\,10^3$~ms)',...
    'Solver ($10\,10^3$~ms)',...
    'Collision Detection ($10\,10^3$~ms)',...
    'Initialization ($10\,10^3$~ms)',...
    'Broad Phase ($10\,10^3$~ms)' ,...
    'Narrow Phase ($10\,10^3$~ms)',...
    'Contact Reduction ($10\,10^3$~ms)'...
    'Other ($10\,10^3$~ms)'
    };

procentage_labels = {...
    'Total ($\%$ of total time)',...
    'Solver ($\%$ of total time)',...
    'Collision Detection ($\%$ of total time)',...
    'Initialization ($\%$ of total time)',...
    'Broad Phase ($\%$ of total time)' ,...
    'Narrow Phase ($\%$ of total time)',...
    'Contact Reduction ($\%$ of total time)'...
    'Other ($\%$ of total time)'
    };

mixed_labels = {...
    'Total ($10\,10^3$~ms)',...
    'Solver ($\%$ of total time)',...
    'Collision Detection ($\%$ of total time)',...
    'Initialization ($\%$ of total time)',...
    'Broad Phase ($\%$ of total time)' ,...
    'Narrow Phase ($\%$ of total time)',...
    'Contact Reduction ($\%$ of total time)'...
    'Other ($\%$ of total time)'
    };


% filter = 1:8;
% write_subset_latex_tabel(filter, names, time_labels, time_data, 'Total time for overall processes in the simulator for different test scenes.', 'keep')
% write_subset_latex_tabel(filter, names, procentage_labels, procentage_data, 'Procentage of total time for overall processes in the simulator for different test scenes.', 'keep')

filter = [1 2 4 5 6 7];
write_subset_latex_tabel(filter, scenes, mixed_labels, mixed_data, 'Total time and procentages for overall processes in the simulator for different test scenes. Initialization includes transformation and refit computations. Narrow phase inlcudes traversal and contact generation times. Observe that generally speaking the whole collision detection takes up 70-80\% of the computation time.', 'keep')


end

